on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dcl_runtime_s3_bucket_key: ${{ steps.publish_dcl_runtime.outputs.s3-bucket-key }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: install
        run:  npm ci
      - name: build
        run:  make build
      - name: test
        run:  make test
      - name: Get the current branch name
        shell: bash
        run: node -e "console.log('::set-output name=branch::' +    ('${{github.head_ref}}' || '$GITHUB_REF'.replace('refs/heads/',''))    )"
        id: myref
      - name: publish packages
        uses: menduz/oddish-action@master
        id: publish_dcl_runtime
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public

          ## publish every package to s3
          s3-bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          s3-bucket-key-prefix: '@dcl/scene-runtime/branch/${{ steps.myref.outputs.branch }}'
          s3-bucket-region: ${{ secrets.SDK_TEAM_AWS_REGION }}
          # ## inform gitlab after publishing to proceed with CDN propagation
          # gitlab-token: ${{ secrets.GITLAB_CDN_DEPLOYER_TOKEN }}
          # gitlab-pipeline-url: ${{ secrets.GITLAB_CDN_DEPLOYER_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}

  notify_deployment:
    needs: [build]
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    name: Deployment Notification
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test this pull request

      - name: Get the current branch name
        shell: bash
        run: node -e "console.log('::set-output name=branch::' +    ('${{github.head_ref}}' || '$GITHUB_REF'.replace('refs/heads/',''))    )"
        id: myref

      - name: Generate S3 URL
        id: url-generator
        run: |
          body=$(echo ${{ secrets.SDK_TEAM_S3_BASE_URL }})/${{ needs.build.outputs.dcl_runtime_s3_bucket_key }}
          echo ::set-output name=body::$body

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test this pull request
            - The `@dcl/scene-runtime` package can be tested in scenes by running
               ```bash
               npm install "${{ steps.url-generator.outputs.body }}"
               ```
          edit-mode: replace
